services:
  - type: web
    name: ctfd-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn CTFd:create_app()
    envVars:
      - key: FLASK_ENV
        value: production
